/*******************************************************************************
Class Name      : SupportServiceImpl
Description     : Main Support Service Implementation
Created By      : Sebastian Torres
Created Date    : 2021-09-17
Modification Log:
---------------------------------------------------------------------------------- 
Developer                   Date                   Description
----------------------------------------------------------------------------------
Sebastian                 2021-09-17              Initial version
*******************************************************************************/
public inherited sharing class SupportServiceImpl implements ISupportService {
  public void setSupportEntitlement(Set<Id> caseIds) {
  }
}
