/*********************************************************************************
Class Name      : ProjectCreateFactory
Description     : Interface used for the strategy pattern to select the right
Created By      : Sebastian Torres
Created Date    : 2021-07-28
Modification Log:
---------------------------------------------------------------------------------- 
Developer                   Date                   Description
----------------------------------------------------------------------------------
Sebastian                 2021-08-05              Initial version
*********************************************************************************/
public without sharing class ProjectCreateFactory {
    public ProjectCreateStrategy() {

    }
}
