/*********************************************************************************
Class Name      : ProjectServiceImpl
Description     : Main Class for project service implementation
Created By      : Sebastian Torres
Created Date    : 2021-07-28
Modification Log:
---------------------------------------------------------------------------------- 
Developer                   Date                   Description
----------------------------------------------------------------------------------
Sebastian                 2021-08-05              Initial version
*********************************************************************************/
public inherited sharing class ProjectsServiceImpl implements IProjectsService {
    
    public void projectCheckout(Set<Id> oppIds) {
        //To be implemented
    }

}